Repository alexandrejuk/mobile-nps, pull requests merged in 2020-03, with the labels that each got.

#27 fix(react-ga): update initialize
  src/index.js
  src/utils/ga/index.js
Labels: bug, mobile-nps, tech

#39 ## Update(names for machines/"L310"/ "L463"/"L620).
  src/utils/api/mocks.js
Labels: mobile-nps, tech

#68 chore: remove collapse component
  src/components/Collapse/Collapse.test.js
  src/components/Collapse/__snapshots__/Collapse.test.js.snap
  src/components/Collapse/index.js
  src/components/Collapse/style.module.css
Labels: cos:standard, mobile-nps, tech

#71 components: add banner component
  src/assets/images/banners/banner-1.svg
  src/components/Banner/Banner.test.js
  src/components/Banner/__snapshots__/Banner.test.js.snap
  src/components/Banner/index.js
  src/components/Banner/style.module.css
  src/components/index.js
  src/stories/components/Banner/index.js
Labels: cos:standard, mobile-nps, tech

#98 chore: remove pull-down reload page
  src/index.css
Labels: bug, cos:standard, tech

#101 chore: fix navigation scroll to top
  src/index.js
  src/pages/Logged/index.js
  src/scrollToTop.js
Labels: bug, cos:standard, mobile-nps, tech
